universe = vanilla
log = log
error = error/$(Process).err

executable = ./hw4_q2.sh
arguments = cB58_Lyman_break.fit 3586
output = output/$(Process).out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/groups/STAT605/boss/cB58_Lyman_break.fit, /home/groups/STAT605/boss/tgz/3586.tgz, http://proxy.chtc.wisc.edu/SQUID/chtc/R361.tar.gz, packages.tar.gz, hw4.R

request_cpus = 1
request_memory = 50GB
request_disk = 2500MB

queue 1
