universe = vanilla
log = log/$(Cluster)_$(Process).log
error = err/$(Cluster)_$(Process).err
output = out/$(Cluster)_$(Process).out

name = 'happy'

executable = print_name.sh
arguments = $(name)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(file)

request_cpus = 1
request_memory = 500MB
request_disk = 100MB

queue file from file
#queue name from names.txt
